---
version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - dupl
    - errname
    - errorlint
    - funlen
    - gocognit
    - goconst
    - gosec
    - misspell
    - prealloc
    - unconvert
  settings:
    funlen:
      lines: 80
      statements: 60
    gocognit:
      min-complexity: 26
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - gocognit
          - goconst
        path: _test.go
      - linters:
          - dupl
        path: pkg/adapter/int.go
      - linters:
          - dupl
        path: pkg/adapter/uint.go
      - path: (.+)\.go$
        text: 'ExampleOrderList refers to unknown identifier: OrderList'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
