---
linters-settings:
  misspell:
    locale: US
  funlen:
    lines: 80
    statements: 60

linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - funlen
    - goconst
    - gosec
    - misspell
    - unconvert
    - prealloc
    - errcheck
    - ineffassign

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
        - funlen
