---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - MAINTAINERS.md
      - LICENSE
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: xmidt-org/.github/.github/workflows/go-ci.yml@go-ci-v1
    with:
      docker-skip: true
      sonarcloud-skip: true
