# SPDX-FileCopyrightText: 2022 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: Apache-2.0
---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'tools/**'
      - '**.md'
      - .gitignore
    tags:
      - 'v*'
  schedule:
    - cron: '28 22 * * 6'

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    uses: goschtalt/.github/.github/workflows/ci.yml@e774129d4a5a31490d5e6714101ca6ee063bcc81
    secrets: inherit
